# Generated by Django 5.0.1 on 2024-01-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('WordID', models.AutoField(primary_key=True, serialize=False)),
                ('Word', models.CharField(max_length=255)),
                ('Transcription', models.CharField(blank=True, max_length=255, null=True)),
                ('Translation', models.CharField(max_length=255)),
                ('Synonyms', models.CharField(blank=True, max_length=255, null=True)),
                ('Examples', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWords',
            fields=[
                ('UserWordID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_api.users')),
                ('WordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_api.words')),
            ],
        ),
    ]
