# Generated by Django 5.0.1 on 2024-01-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='UserWords',
            new_name='UserWord',
        ),
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
