# Generated by Django 5.0.1 on 2024-01-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_api', '0003_words_rename_user_users_userwords_delete_userword_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwords',
            unique_together={('UserID', 'WordID')},
        ),
    ]
